[project]
name = "fastmcp"
dynamic = ["version"]
description = "A more ergonomic interface for MCP servers"
authors = [{ name = "Jeremiah Lowin" }]
dependencies = [
    "httpx>=0.26.0",
    "mcp>=1.0.0",
    "pydantic-settings>=2.6.1",
    "pydantic>=2.5.3",
    "typer>=0.9.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "Apache-2.0" }

[project.scripts]
fastmcp = "fastmcp.cli:app"

[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/fastmcp/_version.py"

[dependency-groups]
dev = [
    "copychat>=0.5.2",
    "ipython>=8.12.3",
    "pdbpp>=0.10.3",
    "pytest-xdist>=3.6.1",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.23.5",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
